version: '3'

services:
  app:
    container_name: claude_container
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./my-app/:/usr/src/app
      - ./.claude/:/root/.claude
    ports:
      - "5000:3000"

